#include "../simple.h"

const SIMPLE_FLOATVECTOR3 SIMPLE_FLOATVECTOR3::ZeroVector = SIMPLE_FLOATVECTOR3();
const SIMPLE_FLOATVECTOR3 SIMPLE_FLOATVECTOR3::UnitVector = SIMPLE_FLOATVECTOR3(1.f);
const SIMPLE_DOUBLEVECTOR3 SIMPLE_DOUBLEVECTOR3::ZeroVector = SIMPLE_DOUBLEVECTOR3();
const SIMPLE_DOUBLEVECTOR3 SIMPLE_DOUBLEVECTOR3::UnitVector = SIMPLE_DOUBLEVECTOR3(1.0);
